alias updbash="source ~/.bash_profile"
alias opnbash="code ~/.bash_profile"

alias g="cd"
alias vs="code"
alias v="nvim"
alias c="clear"
alias d="docker"
alias dc="docker-compose"

alias gdev="cd Desktop/dev"

alias gta="git add"
alias gtaa="git add ."
alias gtcm="git commit -m"
alias gtc="git checkout"
alias gtf="git fetch"
alias gtl="git log"
alias gtpl="git pull"
alias gtp="git push"
alias gtr="git rebase -i origin"
alias gtsq="git rebase -i head~20"
alias gtra="git rebase --abort"
alias gtca="git commit --ammend"
alias gts="git status"
